### ISSUE TITLE
Include images for a program

### ISSUE THREAD

**Issue by michaelarnauts** [tvgrabbers/sourcematching#1]
Some sites provide an image for a specific program. Currently the channel icon is passed in the xml, but this image could be used instead.

Example: https://www.humo.be/tv-gids/uitzending/4585557/kies18

DTD: https://github.com/XMLTV/xmltv/blob/master/xmltv.dtd#L220

**Comment by hikavdh** [comment]
First why post this here?
Secondly: That is not as simple as you put it. I'm not sure the xmltv standard allows for adding an image to a programme. It allows for an url, but an image?? Also At least Mythtv and I guess most other recording programs will ignore it. And last of all I would have to add the possibility to tv_grab_py_API.
